--liquibase formatted sql

--changeset camargo:001-create-order-events-table
CREATE TABLE IF NOT EXISTS order_events (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id UUID NOT NULL UNIQUE,
    customer_id UUID NOT NULL,
    total_amount NUMERIC(12, 2) NOT NULL,
    status VARCHAR(50) NOT NULL,
    received_at TIMESTAMP NOT NULL,
    payload CLOB NOT NULL
);

--changeset camargo:001-create-order-events-index
CREATE INDEX IF NOT EXISTS idx_order_events_customer_id ON order_events (customer_id);

--changeset camargo:001-create-order-event-dlt-table
CREATE TABLE IF NOT EXISTS order_event_dlt (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    event_id UUID NOT NULL UNIQUE,
    failed_at TIMESTAMP NOT NULL,
    failure_reason TEXT NOT NULL,
    payload CLOB NOT NULL
);